import aiohttp
import os
import json
from dotenv import load_dotenv

load_dotenv()

OPENROUTER_API_KEY = os.getenv("OPEN_ROUTER_API_KEY")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "google/gemini-2.5-flash-lite"

TEAM_LISTS = """
Team: mobile_app
Purpose: Features, improvements, bugs, and maintenance related to the mobile application.

Lists:
- backlog: Planned mobile work not currently being worked on.
- current_sprint: Mobile app work actively being developed this sprint.
- bugs: Mobile-specific issues and bug fixes.

Team: integration
Purpose: Integrations between Spequlo and external services, APIs, third-party platforms, deploying to third party platforms, and automation systems.

Lists:
- backlog: Planned integration work set aside for a later date.
- current_sprint: Integration work actively being developed.
- bugs: Integration-specific issues.

Team: internal_tools
Purpose: Internal company tools, admin panels, Discord bots, development utilities, automation scripts, operational tooling, and engineering productivity tools.

Lists:
- backlog: Planned internal tooling work.
- current_sprint: Internal tooling work actively being developed.
- bugs: Internal tool issues.

Team: infrastructure
Purpose: Hosting, servers, deployments, cloud resources, networking, databases, monitoring, CI/CD, security, and platform reliability.

Lists:
- backlog: Planned infrastructure work.
- current_sprint: Infrastructure work actively being worked on.
- bugs: Infrastructure incidents and issues.

Team: website
Purpose: The company's website, landing pages, marketing pages, SEO, and web presence.

Lists:
- list: General website work.

Examples:

"Add login screen to the mobile app"
→ team: mobile_app
→ list_name: current_sprint

"Fix deployment pipeline"
→ team: infrastructure
→ list_name: current_sprint

"Integrate Slack notifications"
→ team: integration
→ list_name: current_sprint

"Add a command to the Discord bot"
→ team: internal_tools
→ list_name: current_sprint

"Update the company landing page"
→ team: website
→ list_name: list
"""

async def classifyIntent(request: dict, user_id: int, user_name: str, assignee_id, assignee_name) -> dict:
        system_prompt = (
            "You are an intent router for a Discord bot managing ClickUp tasks. "
            "You analyze input data to determine user intent, extract exact parameters, "
            "and output structured JSON. "
            "Respond ONLY with a raw valid JSON object. No markdown, no explanation, no preamble."
        )

        user_prompt = rf"""
        Analyze the input data below and output structured JSON.
        
        ## Input Context
        - **Sender:** NAME: {user_name} (ID: {user_id})
        - **Current Message:** "{request["current_message"]}"
        - **Referenced Message:** "{request["referenced_message"]}"
        - **Referenced Metadata:** {json.dumps(request["metadata"])}. If metadata contains `"conversation_type": "clarification"`, treat `original_user_message` as the user's original request and the current message as their answer to `clarifying_question`. Combine both to resolve the full intent and parameters.
        - **Message Assignee Hook:** Name: {assignee_name} | ID: {assignee_id} (Value is "none" if no explicit mention/reply target exists)
        - **Available Workspace Tree:** {TEAM_LISTS}
        
        ---
        
        ## Core Routing Rules
        1. **Metadata Primacy:** Metadata is generated by the bot and is absolute truth. If metadata and message text conflict, prefer metadata.
        2. **Context Resolution:** Resolve pronouns ("it", "that task", "the one you just made") using the `task_id` or `task_name` present in the Referenced Metadata.
        3. **Implicit Continuation:** Do not treat isolated fragment replies (e.g., "Backlog", "Me", "Tomorrow", "Current Sprint") as standalone requests. Combine them with the referenced context to fulfill the previous missing information.
        4. **Create vs Modify:** `modify_task` is triggered by modification verbs (assign, change, move, update, rename, set deadline on, etc.) applied to a task reference. `create_task` is triggered by creation verbs (make, create, add, build, etc.). If the verb is a modification verb but the Referenced Metadata contains no resolvable task, classify as `unclear` — NOT `create_task`.
        5. **Sender as Default Assignee:** For `create_task`, if no other person is mentioned or replied to, the sender is ALWAYS the assignee. Examples:
            - "give me a task to fix X" → assignee_discord_id = SENDER ID
            - "create a task to build Y" → assignee_discord_id = SENDER ID
            - "add a task for the login bug" → assignee_discord_id = SENDER ID
            - "I need to fix Z, make a task" → assignee_discord_id = SENDER ID
            Only leave assignee_discord_id null if the task is explicitly meant for an unnamed/unknown person.
        6. **Assign/Modify Intent Lock:** Verbs like "assign", "give that to", "move that", "change that", "update that" always signal `modify_task` intent, never `create_task` — even if the target task cannot be resolved. If the target is unresolvable, classify as `unclear` and ask which task they mean. Do NOT reclassify as `create_task` simply because no task ID is found.
        
        ---
        
        ## Intent Classification
        Classify the message into exactly one category:
        - `view_tasks`: Request to view assigned tasks.
        - `create_task`: Request to create a new task, including assigning/configuring a task proposed in the current conversation. Must have a clear action item or commitment. No brainstorming or loose ideas.
        - `modify_task`: Request to edit one or more properties of an already-existing ClickUp task (assignee, deadline, priority, list, title, description).
        - `summarize_conversation`: Request to read channel history and produce a summary based on a mode. The mode could be a number of messages, a time period or based on a reply in Referenced Message. If no range specified, default to count=100.
        - `bot_info`: Request for bot capabilities, supported commands, examples, or guidance on how to use the bot.
        - `unclear`: Does not map cleanly, or a required parameter is missing.
        
        ---
        
        ## Parameter Rules
        Extract only what is explicitly present or directly implied. Never invent data.
        
        - **task_id / task_name:** Pull from Referenced Metadata when the user refers to an existing task.
        - **name:** Short and actionable. For `create_task` only.
        - **priority:** 1 = Urgent, 2 = High, 3 = Normal (default), 4 = Low
        - **deadline:** Explicit dates only → YYYY-MM-DD. Never invent.
        - **team / list_name:** Must exactly match Available Workspace Tree. If ambiguous, set both to null.
        - **assignee_discord_id:** 
            - If another person is explicitly mentioned or replied to → use their ID from Message Assignee Hook.
            - If the sender is requesting the task for themselves (any phrasing where no other person is involved) → use SENDER ID.
            - "me", "I'll take it", "assign it to me" → SENDER ID.
            - Only null if the task is explicitly meant for an unspecified or unknown person.
        - **assignee_name:** Follows the same logic as assignee_discord_id but uses the name.
        - **creator_id:** SENDER ID that requested to create a task, not the assignee. For `modify_task`, must come from Referenced Metadata. Never invent.
        - **requestor_id:** SENDER ID that requested a change to an existing task.
        - **mode:** Determines how the conversation range is selected for `summarize_conversation`.
        - **timeframe:** Summarize messages from a specific time period.
        - **count:** Number of recent messages to summarize.
        - **anchor:** Summarize messages starting from a referenced message.
        - **changes:** `modify_task` only. Object containing only the fields the user explicitly wants to change.
        - **remove_assignee:** True when explicitly removing assignment from a task.
        
        ---
        
        ## Confidence & Clarifications
        - `low` if intent is ambiguous or a required parameter is missing. Write a specific, short `clarifying_question`.
        - `high` / `medium` → `clarifying_question: null`.
        - If the user uses a pronoun ("that", "it", "this") to reference a task but Referenced Metadata contains no resolvable task_id or task_name, set confidence to `low` and ask which task they are referring to. Do not attempt to infer or create a task from an unresolved pronoun.
        - For `create_task` and `modify_task` (when list_name is being changed): if `team` and `list_name` cannot be confidently resolved to an exact match in the Available Workspace Tree, ALWAYS set confidence to `low` and ask the user which list they want the task in. Never emit a `create_task` or `modify_task` response with `team: null` or `list_name: null` — treat missing list info the same as a missing required parameter.
        
        ---
        
        ## Pre-Output Validation (run before emitting JSON)
        Before outputting, verify every required field for the classified intent.
        If ANY check fails, override the output to `unclear` with confidence `low`
        and a specific clarifying question — regardless of how confident you are 
        about the intent itself.

        ### create_task required fields:
        - [ ] name → is it resolvable? If null → ask "What should the task be called?"
        - [ ] assignee_discord_id → is it resolvable? If null and no explicit unknown person → ask "Who should this be assigned to?"
        - [ ] team + list_name → both resolvable to Workspace Tree? If not → ask "Which list should this task go in?"

        ### modify_task required fields:
        - [ ] task_id OR task_name → resolvable from metadata or message? If not → ask "Which task are you referring to?"
        - [ ] changes → at least one field present? If empty → ask "What would you like to change about the task?"
        - [ ] team + list_name (only if list is being changed) → resolvable? If not → ask which list.

        ### Rule: Confidence ≠ Intent Clarity
        A message can have a clear intent but still produce `unclear` output.
        "Assign this to me" is clearly `modify_task` in intent, but if `task_id` 
        and `task_name` are both unresolvable, the correct output is still `unclear`.
        Intent confidence and parameter completeness are independent checks.

        ---

        ## Output Format
        Respond ONLY with a raw valid JSON object. No markdown fences, no explanation.
        
        For `view_tasks`:
        {{"intent":"view_tasks","confidence":"high|medium|low","params":{{"assignee_discord_id":"string|null","assignee_name":"string|null"}},"clarifying_question":null}}
        
        For `create_task`:
        {{"intent":"create_task","confidence":"high|medium|low","params":{{"name":"string|null","description":"string|null","priority":"1|2|3|4|null","assignee_discord_id":"string|null","assignee_name":"string|null","deadline":"YYYY-MM-DD|null","team":"string|null","list_name":"string|null","creator_id":"string|null","requestor_id":"string|null"}},"clarifying_question":null}}
        
        For `modify_task`:
        {{"intent":"modify_task","confidence":"high|medium|low","params":{{"task_id":"string|null","task_name":"string|null","creator_id":"string|null","requestor_id":"string|null","changes":{{"name":"string|null","description":"string|null","assignee_discord_id":"string|null","assignee_name":"string|null","deadline":"YYYY-MM-DD|null","priority":"1|2|3|4|null","team":"string|null","list_name":"string|null","remove_assignee":"true|false"}}}},"clarifying_question":null}}
        
        For `summarize_conversation`:
        {{"intent":"summarize_conversation","confidence":"high|medium|low","params":{{"mode":"timeframe|count|anchor","timeframe":"Xh|Xd|Xm|today|null","count":"integer|null"}},"clarifying_question":null}}
        
        For `bot_info`:
        {{"intent":"help","confidence":"high|medium|low","params":{{}},"clarifying_question":null}}
        
        For `unclear`:
        {{"intent":"unclear","confidence":"low","params":{{}},"clarifying_question":"string"}}
        """
        raw = await call_llm([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])
        try:
            clean = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
            result = json.loads(clean)
        except json.JSONDecodeError:
            print("RAW OUTPUT:")
            print(raw)
            raise
        required = {"intent", "confidence", "params", "clarifying_question"}
        missing = required - result.keys()
        if missing:
            raise ValueError(f"Missing fields in classify response: {missing}")
        return result

async def summarizeTranscript(transcript: str) -> dict:
        system_prompt = (
            "You are summarizing a Discord conversation. "
            "Respond ONLY with a raw valid JSON object. No markdown, no explanation, no preamble."
        )
 
        user_prompt = rf"""
        Summarize the Discord conversation below.
        
        ---

        ## Message Format
        Each message follows this format: YYYY-MM-DD HH:MM - DISCORD_ID (DISPLAY_NAME): message
        
        ---

        ## Conversation
        {transcript}
        
        ---
        
        ## Summary Rules
        - Generate a concise summary that captures:
            1. Key decisions made.
            2. Important information shared.
            3. Action items or commitments.
            4. Open questions or unresolved issues.
        - Do not repeat every message.
        - Focus on outcomes, decisions, and important context.
        - Use the DISPLAY_NAME to refer to participants.
        
        ## Output Format
        Respond ONLY with a raw valid JSON object. No markdown fences, no explanation.
        {{"summary":"...","action_items":["..."],"open_questions":["..."]}}
        """

        raw = await call_llm([
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ])
        try:
            clean = raw.strip().removeprefix("```json").removeprefix("```").removesuffix("```").strip()
            result = json.loads(clean)
        except json.JSONDecodeError:
            print("RAW OUTPUT:")
            print(raw)
            raise
        required = {"summary", "action_items", "open_questions"}
        missing = required - result.keys()
        if missing:
            raise ValueError(f"Missing fields in summarize response: {missing}")
        return result

async def call_llm(messages: list[dict]) -> str:
    headers = {
        "Authorization": f"Bearer {OPENROUTER_API_KEY}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/Spequlo/Spequlo-Discord-Bot",  
        "X-Title": "Dipersa", 
    }
    payload = {
        "model": MODEL,
        "messages": messages,
        "max_tokens": 1024
    }
    async with aiohttp.ClientSession() as session:
        async with session.post(OPENROUTER_BASE_URL, headers=headers, json=payload) as response:
            data = await response.json()
            if "choices" not in data:
                print("OpenRouter error response:", data)
                raise ValueError(f"Unexpected response from OpenRouter: {data}")
            return data["choices"][0]["message"]["content"]
        



# 4. **Create vs Modify:** If the user references "this task" / "that task" but Referenced Metadata contains no existing ClickUp task ID or name, the reference points to something proposed in the current conversation → classify as `create_task`, not `modify_task`. `modify_task` requires a task that already exists in ClickUp.