from google import genai
from google.genai import types
import os
import json
from dotenv import load_dotenv

load_dotenv()

TEAM_LISTS = """
Team: mobile_app
Purpose: Features, improvements, bugs, and maintenance related to the mobile application.

Lists:
- backlog: Planned mobile work not currently being worked on.
- current_sprint: Mobile app work actively being developed this sprint.
- bugs: Mobile-specific issues and bug fixes.

Team: integration
Purpose: Integrations between Spequlo and external services, APIs, third-party platforms, deploying to third party platforms, and automation systems.

Lists:
- backlog: Planned integration work set aside for a later date.
- current_sprint: Integration work actively being developed.
- bugs: Integration-specific issues.

Team: internal_tools
Purpose: Internal company tools, admin panels, Discord bots, development utilities, automation scripts, operational tooling, and engineering productivity tools.

Lists:
- backlog: Planned internal tooling work.
- current_sprint: Internal tooling work actively being developed.
- bugs: Internal tool issues.

Team: infrastructure
Purpose: Hosting, servers, deployments, cloud resources, networking, databases, monitoring, CI/CD, security, and platform reliability.

Lists:
- backlog: Planned infrastructure work.
- current_sprint: Infrastructure work actively being worked on.
- bugs: Infrastructure incidents and issues.

Team: website
Purpose: The company's website, landing pages, marketing pages, SEO, and web presence.

Lists:
- list: General website work.

Examples:

"Add login screen to the mobile app"
→ team: mobile_app
→ list_name: current_sprint

"Fix deployment pipeline"
→ team: infrastructure
→ list_name: current_sprint

"Integrate Slack notifications"
→ team: integration
→ list_name: current_sprint

"Add a command to the Discord bot"
→ team: internal_tools
→ list_name: current_sprint

"Update the company landing page"
→ team: website
→ list_name: list
"""

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

def classifyIntent(request: dict, user_id: int, user_name: str, assignee_id: int | None, assignee_name: str | None):
    prompt = rf"""
    You are an intent router for a Discord bot managing ClickUp tasks. Analyze the input data to determine user intent, extract exact parameters, and output structured JSON.

    ## Input Context
    - **Sender:** {user_name} (ID: {user_id})
    - **Current Message:** "{request["current_message"]}"
    - **Referenced Message:** "{request["referenced_message"]}"
    - **Referenced Metadata:** {json.dumps(request["metadata"])}
    - **Message Assignee Hook:** Name: {assignee_name} | ID: {assignee_id} (Value is "none" if no explicit mention/reply target exists)
    - **Available Workspace Tree:** {TEAM_LISTS}

    ---

    ## Core Routing Rules
    1. **Metadata Primacy:** Metadata is generated by the bot and is absolute truth. If metadata and message text conflict, prefer metadata.
    2. **Context Resolution:** Resolve pronouns ("it", "that task", "the one you just made") using the `task_id` or `task_name` present in the Referenced Metadata.
    3. **Implicit Continuation:** Do not treat isolated fragment replies (e.g., "Backlog", "Me", "Tomorrow", "Current Sprint") as standalone requests. Combine them with the referenced context to fulfill the previous missing information.
    4. 4. **Create vs Modify:** If the user references "this task" / "that task" but Referenced Metadata contains no existing ClickUp task ID or name, the reference points to something proposed in the current conversation → classify as `create_task`, not `modify_task`. `modify_task` requires a task that already exists in ClickUp.
    ---

    ## Intent Classification
    Classify the message into exactly one category:
    - `view_tasks`: Request to view assigned tasks.
    - `create_task`: Request to create a new task, including assigning/configuring a task proposed in the current conversation. Must have a clear action item or commitment. No brainstorming or loose ideas.
    - `change_status`: Request to update an existing task's status.
    - `modify_task`: Request to edit one or more properties of an **already-existing** ClickUp task (assignee, deadline, priority, list, title, description).
    - `summarize_conversation`: Request to read channel history and produce a summary.
    - `unclear`: Does not map cleanly, or a required parameter is missing.

    ---

    ## Parameter Rules
    Extract only what is explicitly present or directly implied. Never invent data.

    - **task_id / task_name:** Pull from Referenced Metadata when the user refers to an existing task.
    - **name:** Short and actionable. For `create_task` only.
    - **priority:** 1 = Urgent, 2 = High, 3 = Normal (default), 4 = Low
    - **deadline:** Explicit dates only → YYYY-MM-DD. Never invent.
    - **team / list_name:** Must exactly match Available Workspace Tree. If ambiguous, set both to null.
    - **assignee:** Use Message Assignee Hook if present. "me" / "I'll take it" → Sender. Otherwise null.
    - **status:** `change_status` only. Use the exact string from the user's message.
    - **changes:** `modify_task` only. Object containing only the fields the user explicitly wants to change.

    ---
        
    ## Confidence & Clarifications
    - `low` if intent is ambiguous or a required parameter is missing. Write a specific, short `clarifying_question`.
    - `high` / `medium` → `clarifying_question: null`. Do not ask if Referenced Metadata already resolves the ambiguity.

    ---

    ## Output Format
    Respond ONLY with a raw, valid JSON object matching the schema below. No markdown formatting fences (e.g., do not wrap in ```json), no conversational prefixes, no trailing explanations.
    The `params` shape depends on intent:

    view_tasks:
    {{
        "intent":"view_tasks",
        "confidence":"high|medium|low",
        "params":{{
            "assignee_discord_id":"string|null",
            "assignee_name":"string|null"
        }},
        "clarifying_question":null
    }}

    create_task:
    {{
        "intent":"create_task",
        "confidence":"high|medium|low",
        "params":{{
            "name":"string|null",
            "description":"string|null",
            "priority":"1|2|3|4|null",
            "assignee_discord_id":"string|null",
            "assignee_name":"string|null",
            "deadline":"YYYY-MM-DD|null",
            "team":"string|null",
            "list_name":"string|null"
        }},
        "clarifying_question":null
    }}

    change_status:
    {{
        "intent":"change_status",
        "confidence":"high|medium|low",
        "params":{{
            "task_id":"string|null",
            "task_name":"string|null",
            "status":"string|null"
        }},
        "clarifying_question":null
    }}

    modify_task:
    {{
        "intent":"modify_task",
        "confidence":"high|medium|low",
        "params":{{
            "task_id":"string|null",
            "task_name":"string|null",
            "changes":{{
                "name":"string|null",
                "description":"string|null",
                "assignee_discord_id":"string|null",
                "assignee_name":"string|null",
                "deadline":"YYYY-MM-DD|null",
                "priority":"1|2|3|4|null",
                "team":"string|null",
                "list_name":"string|null",
            }}
        }},
        "clarifying_question":null
    }}

    summarize_conversation:
    {{
        "intent":"summarize_conversation",
        "confidence":"high|medium|low",
        "params":{{}},
        "clarifying_question":null
    }}

    unclear:
    {{
        "intent":"unclear",
        "confidence":"low",
        "params":{{}},
        "clarifying_question":"string"
    }}
    """

    try:
        response = client.models.generate_content(model="gemini-2.5-flash-lite", contents=prompt, config=types.GenerateContentConfig(response_mime_type="application/json"))
        text = response.text
        if text is None:
            raise ValueError("Gemini returned an empty response")
        text = text.strip()
        result = json.loads(text)

        required = {"intent", "confidence", "params", "clarifying_question"}
        missing = required - result.keys()

        if missing:
            raise ValueError(f"Missing fields: {missing}")

        return result
    except Exception as e:
        error_text = str(e)

        if "429" in error_text:
            raise RuntimeError("RATE_LIMIT")
        elif "503" in error_text:
            raise RuntimeError("SERVICE_UNAVAILABLE")
        elif "RESOURCE_EXHAUSTED" in error_text:
            raise RuntimeError("QUOTA_EXCEEDED")
        raise

